services:
  postgres:
    image: postgres:15-alpine
    container_name: is3-devportal-postgres
    environment:
      POSTGRES_DB: backstage
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backstage"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backstage

networks:
  backstage:
    driver: bridge

volumes:
  postgres_data:
    driver: local
